Attempting fix at CI error
When Travis is run, the following error will occur:

core/spec/shoes/logger/ruby_spec.rb
shoes-core/spec/shoes/ui/picker_spec.rb
jruby: warning: unknown property jruby.cext.enabled
jruby: warning: unknown property jruby.cext.enabled
RuntimeError: can't modify frozen Hash
                 []= at org/jruby/RubyHash.java:1001
  define_shoes_color at
/home/travis/build/shoes/shoes4/shoes-core/lib/shoes/color/dsl.rb:156

I believe this may have been caused by using the freeze method on the
colors hash. As such, removing the freeze method for this instance.